### ISSUE TITLE
tokenize(tokenizer.eos_token) doesn't behave as expected

### ISSUE THREAD

**Issue by jeffchy** [QwenLM/Qwen-7B#24]
tokenize.encode(tokenizer.eos_token) != tokenizer.eos_token_id

**Comment by jklj077** [comment]
Control tokens, such as the eos token, are special type of tokens that have specific meanings and are treated differently from regular text tokens. In order to prevent injection attacks, the verbatim text of a control token or any other control token is processed and tokenized as regular text. To use a control token, you should add the corresponding token ID directly to the tokenized text.

**Comment by jeffchy** [comment]
NB

**Comment by jeffchy** [comment]
我反正已经改掉了所以无所谓，但不少新朋友都反馈不太方便，很多已有的训练的轮子都要小修小补。
而且会有人没有意识到这个，导致时间的浪费，训练后出现错误的结果。
至少给一个选项，谢谢。

**Comment by jeffchy** [comment]
ok，改的挺快的，🐂
